# Generated by Django 5.0.4 on 2024-04-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0002_remove_institucion_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credito', to='amt.institucion'),
        ),
    ]
