# Generated by Django 5.0.4 on 2024-04-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0003_alter_credito_institucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='amt.institucion'),
        ),
    ]
