# Generated by Django 5.0.4 on 2024-04-30 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0005_alter_admin_options_alter_admin_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='institucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administradores', to='amt.institucion'),
        ),
    ]
