# Generated by Django 5.0.4 on 2024-04-30 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0006_alter_admin_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('tiempo', models.IntegerField()),
                ('interes', models.FloatField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='amt.institucion')),
            ],
        ),
    ]
