# Generated by Django 5.0.4 on 2024-04-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amt', '0007_inversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
